name: cli-jobs-pipelines-autompg
on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - run-job.sh
      - setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      continue-on-error: true
    - name: run job
      run: bash -x ../../run-job.sh pipeline.yml
      working-directory: jobs/pipeline
